// FETCH CONNECTED USER
export const FETCH_USER_INIT = 'FETCH_USER_INIT';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

// AUTH ACTIONS
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

// UPDATE USER
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';